name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Install dependencies
      run: bundle install
    
    - name: Run linter
      run: bundle exec rubocop
    
    - name: Run tests
      run: bundle exec rspec
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.ruby-version == '3.2'
      with:
        file: ./coverage/coverage.xml

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: bundle install
    
    - name: Run security audit
      run: |
        gem install bundler-audit
        bundle audit check --update